- cis_foundation/cis_foundation_standard.tf
- cloudtrail/s3.tf
Enabling the UnauthorizedAPICalls alarm revealed a missing permission for the config s3 bucket.
> isolate names of metrics and their alarms

- cost_anomoly_detection.tf
- modules/ce_anomoly_detection/main.tf
- modules/ce_anomoly_detection/outputs.tf
- modules/ce_anomoly_detection/terraform.tf
- modules/ce_anomoly_detection/variables.tf
- variables.tf
Notify team when unexpected costs occur
Fixes MLPAB-132
- Create a module to set up cost anomaly detection
- Configure weekly email notifications to the team
- Configure SNS daily alerts for alerting
- Requires an upgrade of the terraform aws provider to v4
- Requires a new global (us-east-1) provider
Note:
Creating AWS CE (Cost Explorer) Anomaly Subscription (): ValidationException: Daily or weekly frequencies only support Email subscriptions
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_anomaly_monitor
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_anomaly_subscription
> MLPAB-132 - Create AWS Cost Explorer anomaly detection #major

- modules/config/sns.tf
- modules/config/variables.tf
AWS Config rule names are limited to 64 characters.
`Error: expected length of name to be in the range (0 - 64), got ...`
the local used includes `aws-config` which is superfluous due to it being used mostly with AWS Config resources. There is one exception which is where it's used for the SNS topic name for AWS Config.
Removing `aws-config` from the local leaves more space for longer product names
Fixes MLPAB-239
- remove aws-config from config_name as its only used in the conftext of aws config resources
- add `aws-config` to SNS topic name
> MLPAB-239 - Fix rule name length error

- .terraform.lock.hcl
- modules/config/s3.tf
- modules/config/variables.tf
- modules/region/config.tf
Server access logging provides detailed records of requests made to a bucket. Server access logs can assist in security and access audits. For more information, see [Security Best Practices for Amazon S3: Enable Amazon S3 server access logging](https://docs.aws.amazon.com/AmazonS3/latest/dev/security-best-practices.html).
- Add logging to the access logging bucket for config s3 bucket
> MLPAB-282 - Add S3 bucket server access logging to config bucket

- modules/config/s3.tf
The current naming convention used for AWS Config S3 buckets prevents the use of the proproduction account's name in full due to using a fully qualified domain name (FQDN) format. This format contradicts best practice guidelines from AWS on S3 bucket naming. [See ADR 0004 on org infra](https://github.com/ministryofjustice/opg-org-infra/blob/main/docs/architecture/decisions/0004-s3-bucket-naming-for-best-compatability.md).
- rename AWS Config S3 bucket to match the format `<aws_service/opg_function>-<aws_region_name>-<account_name>-<product_name>-opg`
This is a major upgrade as renaming S3 buckets is destroy/create process.
The recommendation is that when upgrading to this version, run a `terraform state rm` operation on the existing S3 bucket to remove it from terraform management and …
> MLPAB-533 - rename AWS Config bucket #major

- modules/cloudtrail/output.tf
- modules/security_hub/cis_foundation_controls.tf
- modules/security_hub/main.tf
- security_hub.tf
When implementing the module for the first time, planning fails because there is no resource dependency created between securityhub and cloudtrail. The former requires the latter's log group. 
Using an output from the cloudtrail module to provide the log group name should resolve this.
- output the cloudtrail log group name from the cloudtrail module
- use cloudtrail module output as securityhub input
- remove data source
> MLPAB-615 - Fix dependency issue between security hub and cloudtrail modules

- modules/default_roles/main.tf
Adding name to policies in order to be able to reference them in SSO setup
> MLPAB-972 - add name to policies created for the default roles

- .terraform.lock.hcl
- README.md
- modules/security_hub/main.tf
- modules/security_hub/variables.tf
- security_hub.tf
- terraform.tf
- variables.tf
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/securityhub_account#argument-reference
Three new params have been added with defaults that clash with our config and how accounts are setup, so add in vars for these params and swap them to values that dont fail.
Added `lifecycle` policy so any destroy attempts will fail on the plan
> Update security hub account for >= v4.60

- README.md
- modules/cloudtrail/s3.tf
- modules/region/s3_access_logging.tf
- terraform.tf
AWS changed some defaults on [bucket creation in april](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/) which meant creating new buckets for cloudtrail / access logging failed if they didnt exist already.
This PR moves the `ownership_control` and  `acl` setup to own resource blocks so they are created correctly.
*Note:* There does seem to be a time delay on that, so first `apply` might fail due to that
> bucket ownership policy

- README.md
- shield_advanced.tf
- variables.tf
Add a `aws_shield_drt_access_role_arn_association` resource for the aws_srt_support IAM role to allow AWS SRT to access accounts where the `shield_support_role_enabled` variable is set to true and the `modernisation_platform_account` is set to false.
Previously, the IAM role would be created when the `modernisation_platform_account` variable was set to false.
AWS Accounts where the association has been manually created will need to set `shield_support_role_enabled` to true.
> UML-3211 Add an association for DRT access role #major

- README.md
- oam.tf
- variables.tf
If an `oam_xray_sink_identifier_arn` is provided, create a link with that sink for sending XRay traces
#minor
> Add support for OAM links

- variables.tf
By adding a devault value (even if it's null), Terraform no longer considers the variable required
#patch
> Make `oam_xray_sink_identifier_arn` optional

- README.md
- modules/config/config.tf
- modules/config/variables.tf
- modules/region/config.tf
- modules/region/variables.tf
- regions.tf
- variables.tf
Allow to configure AWS Config with DAILY rather than CONTINOUS scanning to reduce config recorder costs in high cadence accounts #minor
> SP-1923 - AWS Configuration Scanning #minor

- account.tf
- variables.tf
MLPAB-2009 - Manage account alias
https://docs.aws.amazon.com/IAM/latest/UserGuide/console_account-alias.html#CreateAccountAlias
Adds `aws_iam_account_alias` to the module.
If you already have an alias that isn't managed you can import this resource
```hcl
import {
to = module.account_module_name.aws_iam_account_alias.main
id = "my-account-alias"
}
```
If you are already managing an alias in org-infra, you can move it
https://developer.hashicorp.com/terraform/language/modules/develop/refactoring
> MLPAB-2009 - manage account alias in module

- README.md
- roles.tf
Deny all as a base blocks all other calls, so swap to the cloudwatch role and instead deny access to the other permissions that role grants to maintain small footprint
> Swap base role back and add deny

- .github/workflows/main.yml
- README.md
- examples/development_account/main.tf
- examples/full_example/main.tf
- examples/production_account/main.tf
- github_oidc_roles.tf
- modules/github_oidc_roles/main.tf
- modules/github_oidc_roles/outputs.tf
- modules/github_oidc_roles/variables.tf
- modules/github_oidc_roles/versions.tf
- roles.tf
- variables.tf
- remove `cloudwatch_reporting` and `billing` from `user_arns`
- these were only used for reporting tooling, so remove them to reduce permissions
- remove billing and cloudwatch related permissions and iam
- add oidc roles for cost data and uptime perms
> OIDC roles

- modules/cloudtrail/s3.tf
- modules/config/s3.tf
- modules/region/s3_access_logging.tf
Cloudtrail S3 bucket
- refactor to address deprecated options
- add lifecycle to abort multipart uploads after 7 days
Config S3 buckets
- refactor to address deprecated options
- add lifecycle to abort multipart uploads after 7 days
S3 Access Logging S3 buckets
- refactor to address deprecated options
- add lifecycle to abort multipart uploads after 7 days
This update requires importing the resources that have already been created.
Here is a a set of import blocks for a single account. Replace the id;s with the correct bucket names for your accounts
```hcl
import {
to = module.development.module.cloudtrail[0].aws_s3_bucket_lifecycle_configuration.bucket
id = "cloudtrail-bucket-name"
}
import {
to = module.development.module.cloudtrail[0].aws_s3_bucket_logging.cloudtrail
id = …
```
> MLPAB-2499  - Abort multipart uploads after 7 days #major

- README.md
- examples/development_account/custom_iam_policies.tf
- examples/development_account/main.tf
- examples/full_example/custom_iam_policies.tf
- examples/full_example/main.tf
- examples/production_account/custom_iam_policies.tf
- examples/production_account/main.tf
- modules/custom_cloudwatch_alarms/data_access_login.tf
- modules/custom_cloudwatch_alarms/variables.tf
- roles.tf
- variables.tf
Access to production data should be auditable and support raising alarms when used
Fixes MLPAB-2915
- Create a data-access role that has view-only access by default
Any tips and tricks, blog posts or tools which helped you. Plus anything notable you've discovered about the Modernising LPA service
> MLPAB-2915 - create data-access role basics

- variables.tf
Unable to apply previous tag as the ARN for the view only policy was incorrect
Fixes MLPAB-2915
- use job-function view only policy 
- https://docs.aws.amazon.com/aws-managed-policy/latest/reference/ViewOnlyAccess.html
> MLPAB-2915 - Fix reference to view only role

- examples/development_account/main.tf
- examples/full_example/main.tf
- examples/production_account/main.tf
- roles.tf
- variables.tf
Onboarding role for new developer/devops so they can't access too much of our estate initially
DDLS-635
Added a new role in a similar way to the others but have put a flag on it as we only want the role in development accounts. 
NA
> DDLS-635 add onboarding role

- modules/kms_key_multi_region/versions.tf
Set minimum version for terraform, not a specific version when used in a sub-module
> fix version in submodule to be a minimum version, not a specific version

- modules/region/s3_access_logging.tf
Lifecycle rule ID says expire after 490 days but is set to 365
Fixes <TICKET-REF>
- adjust to 490 days
> set expire days in s3 access logging bucket to match id name

- modules/security_hub/cis_foundation_controls.tf
Stop automatically resolving alarms related to CIS security hub standards
Fixes MLPAB-3214, OWCP-70
- remove ok actions from CIS alarms so they don't auto resolve
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_metric_alarm#ok_actions-1
> MLPAB-3214 - Do not auto resolve CIS alarms

- modules/security_hub/aws_resource_tagging_standard.tf
Briefly describe the purpose of the change, and/or link to the JIRA ticket for context
Fixes MLPAB-3234
- add security hub subscription for resource tagging standard
- https://docs.aws.amazon.com/securityhub/latest/userguide/standards-tagging.html
- https://registry.terraform.io/providers/hashicorp/aws/5.100.0/docs/resources/securityhub_standards_subscription
> MLPAB-3234 - enable resource tagging standard

- viewer_additional_iam.tf
The viewer role causes errors when used and no AWS managed policy covers the missing permissions
Fixes SP-3107
> SP-3107 - Give additional permissions to viewer role #minor
